[package]
name = "floem-split-proto2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
floem = { git="https://github.com/lapce/floem.git"}
im = "15.1.0"